name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'patch'

template: |
  ## 🚀 What's Changed
  $CHANGES

  ## 📦 Full Changelog
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## 👥 Contributors
  $CONTRIBUTORS

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'docs'
      - 'refactor'
  - title: '📖 Documentation'
    labels:
      - 'documentation'
  - title: '🔧 Other Changes'
    labels:
      - '*'

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&'
no-changes-template: '*No significant changes in this release*'
no-contributors-template: 'No contributors'

sort-by: 'merged_at'
sort-direction: 'descending'
prerelease: false

include-pre-releases: false
exclude-labels:
  - 'skip-changelog'
