changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: '🚀 New Features'
      labels:
        - feature
        - enhancement
    - title: '🐛 Bug Fixes'
      labels:
        - bug
        - fix
    - title: '📚 Documentation'
      labels:
        - documentation
        - docs
    - title: '🔧 Maintenance'
      labels:
        - maintenance
        - chore
    - title: '⚡ Performance'
      labels:
        - performance
    - title: '🎨 Style Changes'
      labels:
        - style
    - title: '🔨 Refactoring'
      labels:
        - refactor
    - title: '🧪 Tests'
      labels:
        - test
        - tests
    - title: '🏗️ Build System'
      labels:
        - build
        - ci
    - title: '📦 Dependencies'
      labels:
        - dependencies
        - deps
    - title: '🔒 Security'
      labels:
        - security
    - title: '🌐 Internationalization'
      labels:
        - i18n
    - title: '♿ Accessibility'
      labels:
        - accessibility
        - a11y
    - title: '💥 Breaking Changes'
      labels:
        - breaking-change
        - breaking
    - title: '🔄 Other Changes'
      labels:
        - '*' 