name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
tag-prefix: ''
version-template: '$MAJOR.$MINOR.$NEXT_PATCH_VERSION$PRERELEASE'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'patch'

template: |
  ## 🚀 What's Changed
  $CHANGES

  ## 📦 Full Changelog
  [$PREVIOUS_TAG...$RESOLVED_TAG]($REPO_COMPARE_URL)

  ## 👥 Contributors
  $CONTRIBUTORS

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'docs'
      - 'refactor'

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
no-changes-template: '*No significant changes in this release*'
no-contributors-template: 'No contributors'

sort-by: 'merged_at'
sort-direction: 'descending'
prerelease: false
